  name: CI flow 
  
  on:
    push:
      branches: [ main ]
    pull_request: 
      types: [opened, synchronize]
  
  jobs:
    build: 
      runs-on: ubuntu-latest

      steps: 
      - name: Checkout code 
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      # - name: Restore cache
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       .next/cache
      #     # Generate a new cache whenever packages or source files change.
      #     key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
      #     # If source files changed but packages didn't, rebuild from a prior cache.
      #     restore-keys: |
      #       ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-

      # This creates a cache key. ‘hashFiles’ generates SHA256 hash of ‘package-lock.json ‘ file in the repository. We create this key to ensure that if the package-lock.json file is changed, a new cache will be created.
      - name: Restore cached dependencies 
        id: cache-restore 
        uses: actions/cache@v3 
        with: 
          # If node_modules is inside src, modify it to ./src/node_modules
          path: ./node_modules 
          key: npm-${{ hashFiles('./package-lock.json') }} 

      - name: Install Node.js dependencies 
        # This IF condition checks if the step with id ‘cache-restore’ was successful in finding the cache or not. If successful, it will skip npm ci step otherwise execute it.
        if: steps.cache-restore.outputs.cache-hit != 'true' 
        # If node_modules is inside src, add command below cd src
        run: | 
          npm ci - ignore-scripts 

      - name: Build with Next.js
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
    
      - name: Lint 
        run: | 
          npm run lint